const goibioData = [
  {
      additional_info: "Room Service|Internet Access|Restaurant|Free Internet",
      area: "Others",
      city: "Manali",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "85",
      hotel_brand: "null",
      hotel_category: "gostays",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly",
      hotel_facilities: "Doctor on Call|Dry Cleaning|Laundry Service Available|Lobby|Parking Facilities Available|Gardens|Dance Performances (on demand)|Catering|Multi Lingual Staff|Wake-up Call / Service|Suitable For Children|Kitchen available (home cook food on request)|Open Air Restaurant / Dining |Veg / Non Veg Kitchens Separate |Vegetarian Food / Jain Food Available|Car Rental|Taxi Services|Food Facility|Internet Access Free|Children's Park|Postal / Parcel Services| Cook Services|Air / Rail Booking|Courier Service|Guide / Sightseeing Service|Internet / Fax (Reception area only)|RO Water Purification System|Parking Facility|Internet Access|Restaurant|Room Service|Fire Exit Signs|Full Time Operation for All 7 Days|Porter Services Available|Security at All Hotel Entrances|Suites",
      hotel_star_rating: "2",
      image_count: "20",
      latitude: "32.1393865",
      locality: "Others",
      longitude: "77.1546599",
      pageurl: "http://www.goibibo.com/hotels/detail/Manali/hn/2242315224277940906/4295794325445028988/na/hq/",
      point_of_interest: "Hadimba Temple|Naggar Village|Himalayan Nyingmapa Gompa|Tibetan Monasteries|Naggar|Van Vihar|Manali 1st Super Market|Manu Temple|Lady Willingdon Hospital|Chandrakhani Pass|Gadham Thekchhokling Gompa|Manali Bus Stand|Civil Hospital|Others|Arjun Gufa|Nehru Kund|Beas Kund|Club House",
      property_id: "HTLGBO1000016238",
      property_name: "Baragarh Regency",
      property_type: "Resort",
      province: "Manali",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::74|critical reviews::13|reviews with images::13",
      room_area: "",
      room_count: "17",
      room_facilities: "Room Service |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Ceiling Fan|Heating Facility (on request) |Internet Connection In Room|Telephone|Shower Facility Available|Breakfast Available (surcharge)| Hot / Cold Running Water|Housekeeping|Desk in Room|Extra Bed, Towels, Linens, Bedding (on request)|Window Opens|Makeup / Shaving Mirror|Safe - In - Room |Hill View from all Rooms|HD / LCD Satellite TV |Sofa Table / Extra Seats |Private Garden|TV|Bathrobes|Mirror|Gas Cylinder - Chargeable|Luggage Rack|Attached Bathroom|Bedside Table|Clothes Hook in Bathroom|Complete Bedding|Daily Room Cleaning|Dustbins|Extra Toilteries on Demand|Modern Toilet Facilities|Room Door Fitted with Lock and Key|Room with Window/Ventilation|Rooms with Attached Bathrooms|Sufficient Lighting|Western Toilet Seat|Breakfast chargeable",
      room_type: "Deluxe Room",
      similar_hotel: "https://www.goibibo.com/hotels/woodchime-homestay-hotel-in-Kullu-5930870781977298889|https://www.goibibo.com/hotels/tall-trees-resort-hotel-in-Manali-4499032344327794322|https://www.goibibo.com/hotels/oakwood-chalet-hotel-in-Manali-1742814392017514773|https://www.goibibo.com/hotels/span-resorts-and-spa-hotel-in-Manali-2255677305027447320|https://www.goibibo.com/hotels/heritage-village-resorts-&-spa-hotel-in-Manali-3016031428709809122|https://www.goibibo.com/hotels/ooak-hotels-hotel-in-Manali-335123651378108523|https://www.goibibo.com/hotels/baba-deluxe-hotel-in-Manali-4603302465717901783|https://www.goibibo.com/hotels/bharhka-countryside-cottage-resort-hotel-in-Manali-2387611382230099445|https://www.goibibo.com/hotels/hilltone-resorts-&-spa-hotel-in-Manali-2862908591311913427",
      site_review_count: "87",
      site_review_rating: "4.0",
      site_stay_review_rating: "Service Quality::3.9|Amenities::3.7|Food and Drinks::3.8|Value for Money::4.1|Location::4.0|Cleanliness::4.1",
      sitename: "goibibo",
      state: "Himachal Pradesh",
      uniq_id: "2c8db027d43a9452a43e88eb30d9f983"
  },
  {
      additional_info: "Room Service|Gym/Spa",
      address: "A-585, Sushant Lok-1 ,Near Iffco Chowk Metro Station, Gurgaon",
      area: "Sushant Lok",
      city: "Gurgaon",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "87",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly 1. All guests requested to carry Valid ID proof for Check Inn. 2. Couple Guests with Local ID's are not allowed to check inn. 3. Cancellation and prepayment policies vary according to room type.",
      hotel_facilities: "Airport Transfer Available / Surcharge|Banquet Facilities|Business Center |Currency Exchange|Doctor on Call|Health Club / Gym Facility Available|Laundry Service Available|Lift / Elevator|Lobby|Parking Facilities Available|Front Desk|Locker Facility|Major Credit Cards Accepted|24 Hour Front Desk|Luggage Storage|Power Backup",
      hotel_star_rating: "0",
      image_count: "17",
      latitude: "28.4720966",
      locality: "Sushant Lok",
      longitude: "77.0725457",
      pageurl: "http://www.goibibo.com/hotels/detail/Gurgaon/hn/1466927038870613796/5361191673431822820/na/hq/",
      point_of_interest: "Sushant Lok|Sahara Mall|Amity International School",
      property_id: "HTLGBO1000015822",
      property_name: "Asian Suites A- 585",
      property_type: "Guest House",
      province: "Gurgaon",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::8|critical reviews::0|reviews with images::2",
      room_area: "14 X 12 Sq.ft.",
      room_count: "18",
      room_facilities: "Room Service |Air Conditioning |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Ceiling Fan|Hairdryer (on request)|Tea Coffee Kettle / Maker|Internet Connection In Room|Telephone|Breakfast Available (surcharge)|Newspapers|Mineral Water| Hot / Cold Running Water|Housekeeping|Extra Bed, Towels, Linens, Bedding (on request)|Breakfast Available|Makeup / Shaving Mirror|Coffee Table|Snacks / Beverage|TV|Room Heater|Mirror|Mini Refrigerator|Utensils (on request)|Attached Bathroom",
      room_type: "Deluxe Room With Free WIFI",
      similar_hotel: "https://www.goibibo.com/hotels/stepinn-iffco-chowk-hotel-in-Gurgaon-6435118679919376344|https://www.goibibo.com/hotels/micasa-suites--hotel-in-Gurgaon-1749416377003897694|https://www.goibibo.com/hotels/the-pearl-hotel-in-Gurgaon-1273003345842398570|https://www.goibibo.com/hotels/sonam-regency-inn-pvt.-ltd-hotel-in-Gurgaon-8913493133834020973|https://www.goibibo.com/hotels/asian-suites-a--584-hotel-in-Gurgaon-3632022144972189490|https://www.goibibo.com/hotels/white-castle-hotel-in-Gurgaon-7589878869279253390|https://www.goibibo.com/hotels/yes-rooms-gold-souk-hotel-in-Gurgaon-2733237716831100695",
      site_review_count: "8",
      site_review_rating: "4.5",
      site_stay_review_rating: "Service Quality::4.7|Amenities::4.7|Food and Drinks::4.3|Value for Money::4.7|Location::4.8|Cleanliness::4.8",
      sitename: "goibibo",
      state: "Haryana",
      uniq_id: "e98f69f889c0235e6dc480e7df6de0de"
  },
  {
      additional_info: "Restaurant|Swimming Pool",
      address: "Cobra Vaddo,Calungate Baga Road, Bardez, Calangute, Goa",
      area: "Calangute Area",
      city: "Goa",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "50",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 10:00 AM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Resort is undergoing minor external repair/maintenance, inconvenience regretted Hotel may charge compulsory gala dinner supplement on Christmas / New Year's eve or other festive periods. Any such supplements need to be paid directly at the hotel.",
      hotel_facilities: "Swimming Pool|Bar / Lounge |Laundry Service Available|Multi Cuisine Restaurant",
      hotel_star_rating: "0",
      image_count: "28",
      latitude: "15.5483979815",
      locality: "Calangute Area",
      longitude: "73.7576337604",
      pageurl: "http://www.goibibo.com/hotels/detail/Goa/hn/8717279093827200968/6611126874555866446/na/hq/",
      point_of_interest: "Anjuna Beach|Calangute Beach|Titos lane, baga|Baga Beach|Calangute Area|North Goa|Calangute Bus Stand|Candolim Beach",
      property_id: "HTLGBO1000004551",
      property_name: "Bevvan Resort",
      property_type: "Resort",
      province: "Goa",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::1|critical reviews::1|reviews with images::1",
      room_area: "",
      room_count: "15",
      room_facilities: "Room Service |Air Conditioning |Cable / Satellite / Pay TV available|Ceiling Fan|Telephone|Mineral Water| Hot / Cold Running Water|Housekeeping|Desk in Room|Window Opens|Makeup / Shaving Mirror|HD / LCD Satellite TV |Sofa Table / Extra Seats |Split A.C's|Mirror|Mini Refrigerator|Luggage Rack|Attached Bathroom",
      room_type: "Standard Room",
      similar_hotel: "https://www.goibibo.com/hotels/sunrise-beach-resort-hotel-in-Goa-5324437641632332663|https://www.goibibo.com/hotels/rbr-suites-hotel-in-Goa-2979003837674379155|https://www.goibibo.com/hotels/la-baga-beach-hotel-hotel-in-Goa-359542027184165900|https://www.goibibo.com/hotels/sai-sharan-guest-house-hotel-in-Goa-5462760035541548851|https://www.goibibo.com/hotels/m.r-goa-hotel-in-Goa-403522389042680582|https://www.goibibo.com/hotels/leisure-cottages-hotel-in-Goa-8192292456216101314|https://www.goibibo.com/hotels/laxmi-guest-house,-calangute-hotel-in-Goa-1150759101499179878|https://www.goibibo.com/hotels/moonlight-calangute-beach-hotel-in-Goa-1824909062047021361",
      site_review_count: "2",
      site_review_rating: "2.5",
      site_stay_review_rating: "Service Quality::2.5|Amenities::2.5|Food and Drinks::1.0|Value for Money::2.5|Location::2.5|Cleanliness::1.0",
      sitename: "goibibo",
      state: "Goa",
      uniq_id: "9b59d00eaffc273d83000ed7dcda0e83"
  },
  {
      additional_info: "",
      address: "Simsa",
      area: "Village Simsa",
      city: "Manali",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "100",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly",
      hotel_facilities: "Doctor on Call|Dry Cleaning|Laundry Service Available|Parking Facilities Available|Local Tour / Travel Desk|Car Rental",
      hotel_star_rating: "2",
      image_count: "4",
      latitude: "32.2236026",
      locality: "Village Simsa",
      longitude: "77.1858995",
      pageurl: "http://www.goibibo.com/hotels/detail/Manali/hn/2242315224277940906/5894044798937879118/na/hq/",
      point_of_interest: "The Mall|Tibetian Monastery|Vashisht Hot Baths|Jagatsuhk|Village Simsa|Chandrakhani Pass|Manali 1st Super Market",
      property_id: "HTLGBO1000007993",
      property_name: "Apple Inn Cottage",
      property_type: "Cottage",
      province: "Manali",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::1|critical reviews::0|reviews with images::0",
      room_area: "",
      room_count: "24",
      room_facilities: "Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Heating Facility (on request) |Telephone| Hot / Cold Running Water",
      room_type: "Deluxe Room",
      similar_hotel: "https://www.goibibo.com/hotels/green-cottages-hotel-in-Manali-3744638858606558314|https://www.goibibo.com/hotels/sunrise-cottage-hotel-in-Manali-2829535257530131241|https://www.goibibo.com/hotels/nihal-cottage---a-unit-of-ride-at-hill-hotel-in-Manali-4646751368358087618|https://www.goibibo.com/hotels/new-paramount-cottage-hotel-in-Manali-8235698902028417861|https://www.goibibo.com/hotels/green-vista-cottages-hotel-in-Manali-5607369050815775976|https://www.goibibo.com/hotels/himalayan-ecstasy-by-dewdrop-hotel-in-Manali-4278742325709721904|https://www.goibibo.com/hotels/rock-villa-manali-hotel-in-Manali-4341008290722172123",
      site_review_count: "1",
      site_review_rating: "5.0",
      site_stay_review_rating: "Service Quality::5.0|Amenities::5.0|Food and Drinks::5.0|Value for Money::5.0|Location::5.0|Cleanliness::5.0",
      sitename: "goibibo",
      state: "Himachal Pradesh",
      uniq_id: "df0971f9c5501af112485ee28b468ce5"
  },
  {
      additional_info: "Internet Access|Restaurant",
      address: "8180 Street No.-6,Arakashan Road,Paharganj",
      area: "Paharganj",
      city: "Delhi",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "63",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Unmarried couples are not allowed for check in. Guests with local Delhi NCR ID will not be allowed for check-in.",
      hotel_facilities: "Internet Access - Surcharge|Laundry Service Available|Parking Facilities Available|Multi Cuisine Restaurant |Local Tour / Travel Desk|Medical Assistance Available|Power Backup",
      hotel_star_rating: "2",
      image_count: "6",
      latitude: "28.6467775",
      locality: "Paharganj",
      longitude: "77.2127353",
      pageurl: "http://www.goibibo.com/hotels/detail/Delhi/hn/2820046943342890302/7309398067370029045/na/hq/",
      point_of_interest: "Gaffar Market|YMCA Institute|Agrasen Boali|Chandni Chowk|Shivaji Stadium|Paharganj|Jantar Mantar|Talkatora Indoor Stadium|Central Delhi|Ajmeri Gate|Karnail Singh Stadium",
      property_id: "HTLGBO1000008281",
      property_name: "Anmol Hotel Pvt.Ltd",
      property_type: "Hotel",
      province: "Delhi",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::56|critical reviews::65|reviews with images::17",
      room_area: "14 X 14 Sq.ft.",
      room_count: "20",
      room_facilities: "Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Ensuite / Private Bathroom|Telephone| Hot / Cold Running Water|Mirror",
      room_type: "Standard Room Non AC",
      similar_hotel: "https://www.goibibo.com/hotels/delhi-continental-hotel-in-Delhi-537225846114838356|https://www.goibibo.com/hotels/delhi-regency-hotel-in-Delhi-3540065430342971623|https://www.goibibo.com/hotels/maanvi-hotel-in-Delhi-6564512803985465151|https://www.goibibo.com/hotels/milan-continental-hotel-in-Delhi-5671806873048848410|https://www.goibibo.com/hotels/royal-plaza--hotel-in-Delhi-2684400212131173324|https://www.goibibo.com/hotels/shiv-palace-hotel-in-Delhi-4140059490961927842|https://www.goibibo.com/hotels/yatri-international-g.h-hotel-in-Delhi-8389725206211534807|https://www.goibibo.com/hotels/delhi-darshan-dx-hotel-in-Delhi-512479384527942098|https://www.goibibo.com/hotels/ashoka-continental-hotel-in-Delhi-152121932889411829|https://www.goibibo.com/hotels/amax-inn-hotel-in-Delhi-7869803794371651536|https://www.goibibo.com/hotels/family-deluxe-hotel-in-Delhi-825809445121504852",
      site_review_count: "121",
      site_review_rating: "2.8",
      site_stay_review_rating: "Service Quality::2.7|Amenities::2.6|Food and Drinks::2.5|Value for Money::2.9|Location::2.9|Cleanliness::2.6",
      sitename: "goibibo",
      state: "Delhi",
      uniq_id: "0c3514344c9cda8718f558e84bdb44ef"
  },
  {
      additional_info: "Room Service|Internet Access",
      address: "Baga Beach, Calangute, Goa",
      area: "Baga Area",
      city: "Goa",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "68",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 02:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Mandatory  Gala Dinner on 31st Dec at Rs. 1500/- per person. Children below 10 years @ Rs. 750 Gala dinner charges directly payable at the hotel No check out allowed on 25 Dec, 31st Dec  and 1 Jan Hotel may charge compulsory gala dinner supplement on Christmas / New Year's eve or other festive periods. Any such supplements need to be paid directly at the hotel.",
      hotel_facilities: "Airport Transfer Available / Surcharge|Bar / Lounge |Internet Access - Surcharge|Laundry Service Available|Lobby|Non Smoking Rooms|Parking Facilities Available|Front Desk|Locker Facility|24 Hour Front Desk|Doorman|Power Backup|Newspapers In Lobby|Family Room|Room Service (24 Hours)",
      hotel_star_rating: "3",
      image_count: "12",
      latitude: "15.5609234692",
      locality: "Baga Area",
      longitude: "73.7497587248",
      pageurl: "http://www.goibibo.com/hotels/detail/Goa/hn/8717279093827200968/3768679679353292888/na/hq/",
      point_of_interest: "North Goa|Calangute Beach|Baga Area|Anjuna Beach|Titos lane, baga|Baga Beach|Calangute Bus Stand|Anjuna Beach Bus Stop",
      property_id: "HTLGBO1000002591",
      property_name: "",
      property_type: "Resort",
      province: "Goa",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::14|critical reviews::2|reviews with images::3",
      room_area: "",
      room_count: "15",
      room_facilities: "",
      room_type: "Semi Deluxe",
      similar_hotel: "https://www.goibibo.com/hotels/agnelo's-inn-hotel-in-Goa-4111512929038580341|https://www.goibibo.com/hotels/sheesha-beach-cottages-hotel-in-Goa-614871737989607146|https://www.goibibo.com/hotels/vincent-guest-house-hotel-in-Goa-3704123428073704753|https://www.goibibo.com/hotels/divine-guest-house-hotel-in-Goa-2954780291135947297|https://www.goibibo.com/hotels/romeos-place-hotel-in-Goa-1492939295441667716|https://www.goibibo.com/hotels/maria-cottages-hotel-in-Goa-4100852397822520469|https://www.goibibo.com/hotels/dee-royal-castle-beach-resort---hotel-in-Goa-3468098055488466180|https://www.goibibo.com/hotels/larios-beach-holidays--hotel-in-Goa-409514612567707149|https://www.goibibo.com/hotels/baga-yotel-hotel-in-Goa-8247813163062531116|https://www.goibibo.com/hotels/yesho-holidays,-baga-hotel-in-Goa-4500141385606030184|https://www.goibibo.com/hotels/atharv-coastal-end-guest-house-hotel-in-Goa-2023641376376684378|https://www.goibibo.com/hotels/stanleys-guest-house-baga-hotel-in-Goa-1773695945786631356|https://www.goibibo.com/hotels/amoura-beach-resort--hotel-in-Goa-4625656295821698199|https://www.goibibo.com/hotels/cavala-seaside-resort-hotel-in-Goa-7086852492216111810",
      site_review_count: "16",
      site_review_rating: "3.9",
      site_stay_review_rating: "Service Quality::3.9|Amenities::3.8|Food and Drinks::4.7|Value for Money::3.9|Location::4.4|Cleanliness::4.6",
      sitename: "goibibo",
      state: "Goa",
      uniq_id: "9250fc9e71eb1b99830b039492310c60"
  },
  {
      additional_info: "Free Internet",
      address: "K-69, Kalkaji",
      area: "Kalkaji",
      city: "Delhi",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly",
      hotel_facilities: "Doctor on Call|Lobby|Front Desk|Power Backup|Internet Access Free|Newspapers In Lobby",
      hotel_star_rating: "2",
      image_count: "3",
      latitude: "28.5403197",
      locality: "Kalkaji",
      longitude: "77.2613326",
      pageurl: "http://www.goibibo.com/hotels/detail/Delhi/hn/2820046943342890302/4322682276577382235/na/hq/",
      point_of_interest: "Tughlakabad Fort|South Delhi|Masjid Moth|IIBMS|Lotus Temple|District Court Saket|Lajpat Nagar Market|Indraprastha Apollo Hospitals|Jamia Millia Islamia|Moolchand Medcity|ISKCON Temple|Lajpat Nagar|Batra Hospital &amp; Medical Research Centre|Fortis La Femme|Fortis Escorts Heart Institute &amp; Research Centre|Pushpawati Singhania Research Institute|Siri Fort|Kalkaji|Batra Hospital & Medical Research Centre|Fortis Escorts Heart Institute & Research Centre",
      property_id: "HTLGBO1000016284",
      property_name: "Balaji Residency",
      property_type: "Hotel",
      province: "Delhi",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "10",
      room_facilities: "Basic Bathroom Amenities|Hairdryer (on request)|Internet Connection In Room| Hot / Cold Running Water|Housekeeping|Makeup / Shaving Mirror|Attached Bathroom",
      room_type: "Deluxe A/C Room",
      similar_hotel: "https://www.goibibo.com/hotels/le-grand-hotel-in-Delhi-2207951214103114585|https://www.goibibo.com/hotels/grd-inn-hotel-in-Delhi-3948766682880786163|https://www.goibibo.com/hotels/sareen-villa-hotel-in-Delhi-206057762278380883|https://www.goibibo.com/hotels/olive-apartments-c-452,defence-colony-hotel-in-Delhi-8283567430690789378",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Delhi",
      uniq_id: "815a2a40bc6cc2b3161553cb67a33b03"
  },
  {
      additional_info: "Room Service|Internet Access|Restaurant|Free Internet",
      address: "2638-2642 Gurudwara Road,Karol Bagh",
      area: "Karol Bagh Area",
      city: "Delhi",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "76",
      hotel_brand: "null",
      hotel_category: "gostays",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Hotel may charge compulsory gala dinner supplement on Christmas / New Year's eve or other festive periods. Any such supplements need to be paid directly at the hotel.",
      hotel_facilities: "Banquet Facilities|Barbecue Area|Business Center |Concierge|Currency Exchange|Doctor on Call|Dry Cleaning|Laundry Service Available|Lift / Elevator|Lobby|Non Smoking Rooms|Parking Facilities Available|Front Desk|Multi Cuisine Restaurant |Locker Facility|Secretarial Services|Local Tour / Travel Desk|Major Credit Cards Accepted|24 Hour Front Desk|Luggage Storage|Doorman|Medical Assistance Available|Air-Conditioning - Central|Welcome Drinks|Power Backup|Audio - Visual Equipment|Multi Lingual Staff|Wake-up Call / Service|Suitable For Children|Separate Sitting Area|Coffee Shop / Cafe|Conference Facility |ATM / Banking|Veranda|Open Air Restaurant / Dining |Veg / Non Veg Kitchens Separate |Vegetarian Food / Jain Food Available|Car Rental|Express Laundry|Water Dispenser Available|Taxi Services|Board Room|Rooftop Garden|Food Facility| Drivers Rest Room|Internet Access Free|Newspapers In Lobby|Family Room|Room Service (24 Hours)|STD / ISD|Baggage Room|Adjoining Rooms|RO Water Purification System|Outdoor Parking - Secured|Parking Facility|Internet Access|Restaurant|Room Service|CCTV|Full Time Operation for All 7 Days|Paid Transfers|Pest Control Facility|Public Restrooms|Stamps and Mailing Facility",
      hotel_star_rating: "3",
      image_count: "20",
      latitude: "28.6505881342",
      locality: "Karol Bagh Area",
      longitude: "77.1946919955",
      pageurl: "http://www.goibibo.com/hotels/detail/Delhi/hn/2820046943342890302/5862309908432478435/na/hq/",
      point_of_interest: "International Airport|Domestic Airport|New Delhi Railway Station|India Gate|Red Fort|Lotus Temple|Nehru Place|Connaught Place|Jantar Mantar|Qutab Minar|Gurgaon|Birla Mandir|Karol Bagh Metro Station|Noida|Liberty Theatre|Jhandewalan Mandir|Gaffar Market|Shivaji Stadium|Karol Bagh Area|Talkatora Indoor Stadium|Sarai Rohilla Station|Ajmeri Gate|Karnail Singh Stadium|West Delhi",
      property_id: "HTLGBO1000000104",
      property_name: "BB Palace-A Boutique Hotel",
      property_type: "Hotel",
      province: "Delhi",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::452|critical reviews::98|reviews with images::58",
      room_area: "21 X 21 Sq.ft.",
      room_count: "24",
      room_facilities: "Room Service |Air Conditioning |Ensuite / Private Bathroom|Hairdryer (on request)|Tea Coffee Kettle / Maker|Mini bar - On Charge |Internet Connection In Room|Telephone|Voicemail|Shower Facility Available|Newspapers|Reading Lamps|Shower Caps Available|Mineral Water|Premium Beddings / Hypo-Allergenic | Hot / Cold Running Water|Housekeeping|Desk in Room|Breakfast Available|Window Opens|Makeup / Shaving Mirror|Wardrobe|HD / LCD Satellite TV |Sofa Table / Extra Seats |Bathrobes|Mirror|Luggage Rack",
      room_type: "Club Room",
      similar_hotel: "https://www.goibibo.com/hotels/eliza-continental-hotel-in-Delhi-7162813811653471497|https://www.goibibo.com/hotels/ahluwalia-palace-hotel-in-Delhi-8167612303475571960|https://www.goibibo.com/hotels/-hotel-kabila-hotel-in-Delhi-4588528976528098651",
      site_review_count: "550",
      site_review_rating: "4.0",
      site_stay_review_rating: "Service Quality::4.0|Amenities::3.9|Food and Drinks::4.1|Value for Money::4.0|Location::4.0|Cleanliness::4.1",
      sitename: "goibibo",
      state: "Delhi",
      uniq_id: "04e102bdd434eaeec45f095aac031106"
  },
  {
      additional_info: "",
      address: "85, gomes defence, III rd Avenue, vaishali nagar, Jaipur, Rajasthan",
      area: "Others",
      city: "Jaipur",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "0",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 02:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly  Hotel may charge gala dinner supplement on Christmas/New Years eve or other festive periods. Which needs to be paid directly at the hotel.As per the govt. guidelines valid govt. issued id proofs are required to be presented at the Time of C/in.",
      hotel_facilities: "Doctor on Call|Lobby|Front Desk|Local Tour / Travel Desk",
      hotel_star_rating: "1",
      image_count: "5",
      latitude: "26.9047751",
      locality: "Others",
      longitude: "75.7488641",
      pageurl: "http://www.goibibo.com/hotels/detail/Jaipur/hn/4278754392716898526/2733323897862092484/na/hq/",
      point_of_interest: "Others|K.L. Saini Stadium|BAPS Shri Swaminarayan Mandir",
      property_id: "HTLGBO1000061958",
      property_name: "Art Inn Homestay",
      property_type: "Homestay",
      province: "Jaipur",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::1|critical reviews::0|reviews with images::0",
      room_area: "",
      room_count: "2",
      room_facilities: "Room Service |Air Conditioning |Cable / Satellite / Pay TV available|Ceiling Fan|Mineral Water|Attached Bathroom",
      room_type: "Standared Room",
      similar_hotel: "https://www.goibibo.com/hotels/sarovar-portico-jaipur-hotel-in-Jaipur-3577696740667100068|https://www.goibibo.com/hotels/colonel's-homestead-hotel-in-Jaipur-4583180496451155305|https://www.goibibo.com/hotels/tordi-palace-hotel-in-Jaipur-1678501512604360727|https://www.goibibo.com/hotels/marc-inn-hotel-in-Jaipur-2642570912841244766|https://www.goibibo.com/hotels/seven-seas-hotel-in-Jaipur-207322209378138722|https://www.goibibo.com/hotels/nohra-homestay-hotel-in-Jaipur-576350784450660389|https://www.goibibo.com/hotels/royale-lalit-hotel-hotel-in-Jaipur-3236234342441807440|https://www.goibibo.com/hotels/rawla-rawatsar-hotel-in-Jaipur-1536996533947398425|https://www.goibibo.com/hotels/avana-hotel-in-Jaipur-9217799449466810298",
      site_review_count: "1",
      site_review_rating: "3.0",
      site_stay_review_rating: "Service Quality::4.0|Amenities::2.0|Food and Drinks::3.0|Value for Money::1.0|Location::4.0|Cleanliness::3.0",
      sitename: "goibibo",
      state: "Rajasthan",
      uniq_id: "059fa03383171456eb56f4503d499f6f"
  },
  {
      additional_info: "",
      address: "51 Amri Nagar south ex",
      area: "South Extension",
      city: "Delhi",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 02:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Booking rates will not be valid for Christmas  New year dates, High season  long weekend dates  extra supplement will be charged over  above the paid rates as per actual  hotel discretion",
      hotel_facilities: "Doctor on Call|Front Desk|24 Hour Front Desk",
      hotel_star_rating: "0",
      image_count: "6",
      latitude: "28.5732907",
      locality: "South Extension",
      longitude: "77.2219418",
      pageurl: "http://www.goibibo.com/hotels/detail/Delhi/hn/2820046943342890302/6345938336663021173/na/hq/",
      point_of_interest: "Safdarjung Station|Hungary Embassy|Dilli Haat|AIIMS|R. K. Khanna Tennis Stadium|Khan Market|ISKCON Temple|AASHLOK Hospital|Thyagaraj Sports Complex|Japanese Embassy|INA Market|French Cultural Center in India|South Extension|Hauz Khas|Lajpat Nagar Market|Embassy of Spain|Lajpat Nagar|Lodhi Gardens|Metro Station Hauz Khas|Deer Park|Embassy of The Arab Republic of Egypt|Masjid Moth|Hazrat Nizammudin Railway Station|Ethiopia Embassy|Humayuns Tomb|Jawaharlal Nehru Stadium|Moolchand Medcity|Sarojini Nagar Market|Safdarjang Hospital|Embassy of Israel|Siri Fort|Brazil Embassy",
      property_id: "HTLGBO1000073032",
      property_name: "Arjun Homestay",
      property_type: "Homestay",
      province: "Delhi",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "4",
      room_facilities: "Room Service |Basic Bathroom Amenities",
      room_type: "Deluxe",
      similar_hotel: "https://www.goibibo.com/hotels/skylink-suites-hotel-in-Delhi-8067768056618606410|https://www.goibibo.com/hotels/jagannath-guest-house-hotel-in-Delhi-4333356750051129564|https://www.goibibo.com/hotels/comfort-bnb-hotel-in-Delhi-6503303861583884599|https://www.goibibo.com/hotels/kumar-bed-and-breakfast-hotel-in-Delhi-1612806011154902478|https://www.goibibo.com/hotels/leefa-home-hotel-in-Delhi-8986732768093317560|https://www.goibibo.com/hotels/olive-service-apartments-defence-colony-hotel-in-Delhi-5047317835166572542|https://www.goibibo.com/hotels/the-loft-bed-&-breakfast-hotel-in-Delhi-3160296891576504057|https://www.goibibo.com/hotels/boribista-backpacking-hostel-hotel-in-Delhi-6946691218408031797|https://www.goibibo.com/hotels/lotus-bed-and-breakfast-hotel-in-Delhi-4671966758568123796",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Delhi",
      uniq_id: "78e97b94135c33b231335c42695149ed"
  },
  {
      additional_info: "Room Service|Free Internet",
      address: "Ashirwad Enclave, Lakhimi Path, Jonali, R.G.Baruah Road,",
      area: "Rg Baruah Road",
      city: "Guwahati",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "90",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly We will require ID proof of all guest including spouses and fiances. Checkout is 12 noon which can be flexible depending on guest booking for that particular day.",
      hotel_facilities: "Business Center |Doctor on Call|Dry Cleaning|Laundry Service Available|Parking Facilities Available|Welcome Drinks|Power Backup|Gardens|Conference Facility |Kitchen available (home cook food on request)|Car Rental|Board Room|Internet Access Free|Newspapers In Lobby|Children's Park| Cook Services|Parking Facility|Room Service",
      hotel_star_rating: "0",
      image_count: "13",
      latitude: "26.1661828147",
      locality: "Rg Baruah Road",
      longitude: "91.7774135711",
      pageurl: "http://www.goibibo.com/hotels/detail/Guwahati/hn/3518826103379012321/8397644275697850789/na/hq/",
      point_of_interest: "Rg Baruah Road|Nehru Stadium|Guwahati Railway Station|Assam State Museum|Guwahati Planetarium",
      property_id: "HTLGBO1000078940",
      property_name: "Ashirwad Homestay",
      property_type: "Hotel",
      province: "Guwahati",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::19|critical reviews::2|reviews with images::7",
      room_area: "",
      room_count: "4",
      room_facilities: "Room Service |Basic Bathroom Amenities|Ceiling Fan|Tea Coffee Kettle / Maker|Mirror",
      room_type: "Deluxe Ac Suite with Kitchentte",
      similar_hotel: "https://www.goibibo.com/hotels/gateway-grandeur-hotel-in-Guwahati-6561419896307870922|https://www.goibibo.com/hotels/parnil-palace-hotel-in-Guwahati-3068634600077791724|https://www.goibibo.com/hotels/vivanta-by-taj--guwahati-hotel-in-Guwahati-7830366016456325811|https://www.goibibo.com/hotels/d-courtyard-hotel-in-Guwahati-8299274684048799913|https://www.goibibo.com/hotels/the-guwahati-address-by-centre-point-hotel-in-Guwahati-6411599690838562609|https://www.goibibo.com/hotels/green-wood-city-point-hotel-in-Guwahati-6995272623196075024|https://www.goibibo.com/hotels/cygnett-inn-repose-hotel-in-Guwahati-444535724340062730|https://www.goibibo.com/hotels/grand-starline-hotel-in-Guwahati-5269209864055818023|https://www.goibibo.com/hotels/plaza-inn-hotel-in-Guwahati-9061188129470452491|https://www.goibibo.com/hotels/pragati-manor-hotel-in-Guwahati-3170337963655938281",
      site_review_count: "21",
      site_review_rating: "4.3",
      site_stay_review_rating: "Service Quality::4.5|Amenities::4.1|Food and Drinks::4.2|Value for Money::4.5|Location::3.9|Cleanliness::4.5",
      sitename: "goibibo",
      state: "Assam",
      uniq_id: "0e82d18692933c36f3be2928b60ab191"
  },
  {
      additional_info: "Room Service|Internet Access|Free Internet",
      address: "Near Botanical Garden Metro Station,Sec  -  46",
      area: "Others",
      city: "NOIDA",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Hotel may charge compulsory gala dinner supplement on Christmas / New Year's eve or other festive periods. Any such supplements need to be paid directly at the hotel.",
      hotel_facilities: "Airport Transfer Available / Surcharge|Doctor on Call|Dry Cleaning|Internet Access - Surcharge|Lift / Elevator|Lobby|Parking Facilities Available|Front Desk|Local Tour / Travel Desk|24 Hour Front Desk|Power Backup|Extra Person / Child - Share the same room|Internet Access Free|Newspapers In Lobby|Room Service (24 Hours)|Parking Facility",
      hotel_star_rating: "0",
      image_count: "0",
      latitude: "28.5522379",
      locality: "Others",
      longitude: "77.3597194",
      pageurl: "http://www.goibibo.com/hotels/detail/NOIDA/hn/2311763083662248959/1894799850509469749/na/hq/",
      point_of_interest: "The Great India Place|Worlds of Wonder|Botanical Garden Metro Station|Noida Golf Course Metro Station|Shipra Mall|Others",
      property_id: "HTLGBO1000003719",
      property_name: "Apna Ghar- Sector 46",
      property_type: "Guest House",
      province: "NOIDA",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "32",
      room_facilities: "Air Conditioning |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Ensuite / Private Bathroom|Iron / Ironing board available|Tea Coffee Kettle / Maker|Internet Connection In Room|Telephone|Safe - In - Room",
      room_type: "Deluxe Room",
      similar_hotel: "https://www.goibibo.com/hotels/sweet-home-hotel-in-NOIDA-2402490913282357923|https://www.goibibo.com/hotels/p.k.-budget-hotel-hotel-in-Noida-8435906838650831317|https://www.goibibo.com/hotels/jnr-hotel-in-Noida-7832958841206258904|https://www.goibibo.com/hotels/peacock-serviced-apartment-hotel-in-Noida-3266294456048534066|https://www.goibibo.com/hotels/jnr-hospitality-hotel-in-Noida-2919353476793245139|https://www.goibibo.com/hotels/tavisha-villa-hotel-in-Noida-952448091406677260",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Uttar Pradesh",
      uniq_id: "7d3a45fb5a5481f4f28975cebc8dd3c0"
  },
  {
      additional_info: "Room Service|Free Internet",
      address: "429, Sector-6, Rohini, Near Vidha Jain Public School",
      area: "Rohini",
      city: "Delhi",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 02:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly We do not allow unmarried / unrelated couples to checkin. This is at full discretion of the hotel management. No refund would be applicable in case the checkin is denied under such circumstances",
      hotel_facilities: "Doctor on Call|Parking Facilities Available|Front Desk|Power Backup|Smoking Area |Internet Access Free|Courier Service|Parking Facility|Room Service",
      hotel_star_rating: "0",
      image_count: "6",
      latitude: "28.7097476",
      locality: "Rohini",
      longitude: "77.1103954",
      pageurl: "http://www.goibibo.com/hotels/detail/Delhi/hn/2820046943342890302/2584506122328817632/na/hq/",
      point_of_interest: "North Delhi|Parsavnath Mall Rohini|Metro Walk|Rohini|Jaipur Golden Hospital|Dr. Baba Saheb Ambedkar Hospital",
      property_id: "HTLGBO1000096488",
      property_name: "Baba Guest House",
      property_type: "Guest House",
      province: "Delhi",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "3",
      room_facilities: "Air Conditioning |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Ceiling Fan|Internet Connection In Room|Telephone|Newspapers| Hot / Cold Running Water|Housekeeping|Desk in Room|Toiletries|Window Opens|TV|Mirror|Daily Room Cleaning|Dustbins|In-room Storage Space|Sufficient Lighting|Western Toilet Seat",
      room_type: "Standard Room",
      similar_hotel: "https://www.goibibo.com/hotels/sai-residency-hotel-in-Delhi-3231814047203636657|https://www.goibibo.com/hotels/yes-sir-guest-house-hotel-in-Delhi-962100547008486621|https://www.goibibo.com/hotels/arnav-residency-hotel-in-Delhi-667281782486641821|https://www.goibibo.com/hotels/naveen-hotel-in-Delhi-1261040609573967596|https://www.goibibo.com/hotels/crowne-plaza-new-delhi-rohini-hotel-in-Delhi-3945737845163126467|https://www.goibibo.com/hotels/amigo-nestaway-hotel-in-Delhi-4347186885385290168|https://www.goibibo.com/hotels/s-r-residency-hotel-in-Delhi-744470371188106401",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Delhi",
      uniq_id: "45a4f01f95a7cf07713692c32efa9f3f"
  },
  {
      additional_info: "",
      address: "Village Gurdorh, Naggar Road, Manali,Distt. Kullu Himachal Pradesh",
      area: "Naggar Road",
      city: "Manali",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly",
      hotel_facilities: "Doctor on Call|Lobby|Parking Facilities Available|Front Desk|24 Hour Front Desk|Gardens",
      hotel_star_rating: "4",
      image_count: "7",
      latitude: "32.2459026",
      locality: "Naggar Road",
      longitude: "77.1880853",
      pageurl: "http://www.goibibo.com/hotels/detail/Manali/hn/2242315224277940906/6092125296876225276/na/hq/",
      point_of_interest: "Naggar Road|Manali 1st Super Market|Chandrakhani Pass|Vashist Hot Water Springs and Temples",
      property_id: "HTLGBO1000054416",
      property_name: "Baragarh Villa",
      property_type: "Villa",
      province: "Manali",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "4",
      room_facilities: "Room Service |Air Conditioning |Cable / Satellite / Pay TV available|Ceiling Fan|Mineral Water|Attached Bathroom",
      room_type: "Royal Suite",
      similar_hotel: "https://www.goibibo.com/hotels/grass-land-hotel-in-Manali-3255506648870796021|https://www.goibibo.com/hotels/vasuki-bnb-inn-hotel-in-Manali-2778386500375296425|https://www.goibibo.com/hotels/moon-manali-hotel-in-Manali-3091196764927485369|https://www.goibibo.com/hotels/heera-invitation-hotel-in-Manali-7136494020422123837|https://www.goibibo.com/hotels/renuka-hotel-in-Manali-5969872767022108555|https://www.goibibo.com/hotels/hillanss-hotel-in-Manali-8566595182038505939|https://www.goibibo.com/hotels/vikrant-inn--hotel-in-Manali-915246746615413630|https://www.goibibo.com/hotels/naina-resort-and-cottages-hotel-in-Manali-3085105072256429055|https://www.goibibo.com/hotels/hill-top-hotel-in-Manali-7475847388138972618|https://www.goibibo.com/hotels/himanshu-resorts-hotel-in-Manali-8906772198782849766|https://www.goibibo.com/hotels/blue-heaven-manali-hotel-in-Manali-6348871136847363006|https://www.goibibo.com/hotels/solang-hotel-in-Manali-6566572254439891847",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Himachal Pradesh",
      uniq_id: "72968b25d39d6fbc47f342fc6ca80cee"
  },
  {
      additional_info: "",
      address: "Titawada, Nerul Bardez Goa",
      area: "Candolim Area",
      city: "Goa",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "92",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 11:00 AM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly AS PER GOVERNMENT DIRECTIVES IT IS MANDATORY FOR ALL GUEST TO SHOW THEIR PHOTO ID AT CHECK IN, WHICH CAN BE IN FORM OF PASSPORT AND VISA COPY/ DRIVING LICENSE/ VOTER ID CARD FAILING WHICH THE HOTEL RESERVES THE RIGHT OF REFUSAL.",
      hotel_facilities: "",
      hotel_star_rating: "0",
      image_count: "8",
      latitude: "15.5049283",
      locality: "Candolim Area",
      longitude: "73.7919103",
      pageurl: "http://www.goibibo.com/hotels/detail/Goa/hn/8717279093827200968/7895665242797159088/na/hq/",
      point_of_interest: "Vintage Hospital And Medical Research Centre|Sinquerim Beach|Shanta Durga Temple|Chichekade Bus Stop|Candolim Bus Stop|Candolim Area|Fort Aguada|Miramar Beach|Kala Academy|North Goa|Candolim Beach",
      property_id: "HTLGBO1000008549",
      property_name: "Annapurna Guest House",
      property_type: "Guest House",
      province: "Goa",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::38|critical reviews::0|reviews with images::3",
      room_area: "",
      room_count: "2",
      room_facilities: "Air Conditioning |Ceiling Fan|Full Kitchen|Refrigerator|Shower Facility Available| Hot / Cold Running Water|Breakfast Available|Coffee Table|Split A.C's|TV|Mirror|Utensils (on request)|Gas Cylinder - Chargeable|Attached Bathroom",
      room_type: "AC 1 BHK",
      similar_hotel: "https://www.goibibo.com/hotels/coco-shambhala-hotel-in-Goa-6025073351876784094|https://www.goibibo.com/hotels/coco-beach-village-hotel-in-Goa-5992311322834936543|https://www.goibibo.com/hotels/aabhaar-holidays-hotel-in-Panaji-9106513622615488488|https://www.goibibo.com/hotels/saramoon-resorts-hotel-in-Goa-1096081956176456686|https://www.goibibo.com/hotels/the-four-leaf-clover-hotel-in-Goa-4187872148952978958|https://www.goibibo.com/hotels/casa-melhor-candolim--hotel-in-Goa-3671957965878434133|https://www.goibibo.com/hotels/deltin-suites-hotel-in-Goa-3842891581714705267|https://www.goibibo.com/hotels/sol-de-goa-hotel-in-Goa-7555639027754239569",
      site_review_count: "38",
      site_review_rating: "4.6",
      site_stay_review_rating: "Service Quality::4.6|Amenities::4.5|Food and Drinks::4.4|Value for Money::4.8|Location::4.4|Cleanliness::4.7",
      sitename: "goibibo",
      state: "Goa",
      uniq_id: "e937f1f395656f529f269d6bc189a52f"
  },
  {
      additional_info: "Room Service|Internet Access|Free Internet",
      address: "Plot No:2,Elcot Avenue,Rajiv Gandhi Road,(OMR),Near Sozhanganallur Signal, before aavin milk factory",
      area: "Thuraipakkam",
      city: "Chennai",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "67",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Most hotels do not allow unmarried / unrelated couples to check-in. This is at full discretion of the hotel management. No refund would be applicable in case the hotel denies check-in under such circumstances .",
      hotel_facilities: "Internet Access - Surcharge|Laundry Service Available|Lift / Elevator|Parking Facilities Available|Front Desk|Locker Facility|Power Backup|Internet Access Free|Room Service (24 Hours)|Outdoor Parking - Secured",
      hotel_star_rating: "0",
      image_count: "3",
      latitude: "12.8944628",
      locality: "Thuraipakkam",
      longitude: "80.2273584",
      pageurl: "http://www.goibibo.com/hotels/detail/Chennai/hn/4354390963378411938/5838534518404123141/na/hq/",
      point_of_interest: "Thuraipakkam",
      property_id: "HTLGBO1000016892",
      property_name: "ARAVINDAR RESIDENCY",
      property_type: "Hotel",
      province: "Chennai",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::22|critical reviews::6|reviews with images::2",
      room_area: "10 X 10 Sq.ft.",
      room_count: "22",
      room_facilities: "Air Conditioning |Basic Bathroom Amenities|Ceiling Fan|Ensuite / Private Bathroom| Hot / Cold Running Water|Housekeeping|Toiletries|TV|Mirror",
      room_type: "Deluxe Room",
      similar_hotel: "https://www.goibibo.com/hotels/hibiscus-guest-house-hotel-in-Chennai-3824440894254245445|https://www.goibibo.com/hotels/sholling-residency-hotel-in-Chennai-4800877195963428219|https://www.goibibo.com/hotels/royal-stay-service-apartments(sholinganallur)---hotel-in-Chennai-7574571620646941482|https://www.goibibo.com/hotels/tgi-inn-iberis-hotel-in-Chennai-6471868231929375432|https://www.goibibo.com/hotels/catch22-hospitality-services-,-omr-sholinganallur-hotel-in-Chennai-4581462990314698922|https://www.goibibo.com/hotels/aloft-chennai-omr-it-expressway-hotel-in-Chennai-6396698582902360500",
      site_review_count: "28",
      site_review_rating: "3.6",
      site_stay_review_rating: "Service Quality::3.5|Amenities::3.7|Food and Drinks::3.4|Value for Money::3.8|Location::4.0|Cleanliness::3.8",
      sitename: "goibibo",
      state: "Tamil Nadu",
      uniq_id: "6c400590e2262416abddeccb148f439f"
  },
  {
      additional_info: "Room Service|Internet Access",
      address: "Chitrasani Village, Off. Abu-Palanpur Highway No. 14, Banaskantha, Gujarat",
      area: "Banaskantha",
      city: "Chitrasani",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "0",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly *Valid Identification Documents/ Proof are Mandatory. *In case of any unusual/ improper/ suspicious act, Hotel can cancel Room. *Unmarried and unrelated couples will not be allowed to check in due to security reason. *Customer has to carry a copy of booking voucher at the time of check in. *Check Inn and Check Out is 12:00 Noon. After that half day charges will be applicable. *Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel.  *Pets are not allowed.",
      hotel_facilities: "Banquet Facilities|Doctor on Call|Internet Access - Surcharge|Laundry Service Available|Lift / Elevator|Lobby|Parking Facilities Available|Front Desk|Locker Facility|Major Credit Cards Accepted|Doorman|Wake-up Call / Service|Car Rental|Guide / Sightseeing Service|Room Service",
      hotel_star_rating: "3",
      image_count: "17",
      latitude: "24.26778",
      locality: "Banaskantha",
      longitude: "72.483507",
      pageurl: "http://www.goibibo.com/hotels/detail/Chitrasani/hn/8270415669473346029/858028934194279477/na/hq/",
      point_of_interest: "Banaskantha",
      property_id: "HTLGBO1000059384",
      property_name: "Balaram Palace Resort",
      property_type: "Palace",
      province: "Chitrasani",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::0|critical reviews::1|reviews with images::0",
      room_area: "",
      room_count: "21",
      room_facilities: "Room Service |Air Conditioning |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Telephone|Shower Facility Available| Hot / Cold Running Water|Housekeeping|Toiletries|Safe - In - Room |Wardrobe|HD / LCD Satellite TV |Mirror|Dressing Area|Luggage Rack|Attached Bathroom|Complete Bedding|Curtains/Shades|Daily Room Cleaning|Do-Not-Disturb Notice|Dustbins|Extra Toilteries on Demand|Sufficient Lighting|Western Toilet Seat",
      room_type: "Royal Tent",
      similar_hotel: "",
      site_review_count: "1",
      site_review_rating: "1.0",
      site_stay_review_rating: "Service Quality::1.0|Amenities::1.0|Food and Drinks::1.0|Value for Money::1.0|Location::1.0|Cleanliness::1.0",
      sitename: "goibibo",
      state: "Gujarat",
      uniq_id: "06fd2432c131b986e3dabef63869e0fe"
  },
  {
      additional_info: "Room Service",
      address: "Village Savti, Dharampuri, P.O. Daulatpura, Distt. Khandar",
      area: "Ranthambhore",
      city: "Sawai Madhopur",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly We do not allow unmarried / unrelated couples to checkin. This is at full discretion of the hotel management. No refund would be applicable in case the checkin is denied under such circumstances.",
      hotel_facilities: "Doctor on Call|24 Hour Front Desk|Room Service (24 Hours)|Room Service|CCTV",
      hotel_star_rating: "0",
      image_count: "6",
      latitude: "26.0065687",
      locality: "Ranthambhore",
      longitude: "76.6037222",
      pageurl: "http://www.goibibo.com/hotels/detail/Sawai Madhopur/hn/8314560716455433059/7084914320933501817/na/hq/",
      point_of_interest: "Ranthambhore",
      property_id: "HTLGBO1000048022",
      property_name: "Bhadrawati Safari Lodge",
      property_type: "Lodge",
      province: "Sawai Madhopur",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "10",
      room_facilities: "Air Conditioning |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Telephone|Newspapers",
      room_type: "Luxury Room",
      similar_hotel: "",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Rajasthan",
      uniq_id: "ea07c562f673b643f273ce04dfa9e893"
  },
  {
      additional_info: "Room Service|Free Internet",
      address: "NT Mall Road, Dalhousie ,176304(HP)",
      area: "The Mall",
      city: "Dalhousie",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "84",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 01:00 PM and the standard check-out time is 11:30 AM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly We do not allow unmarried / unrelated couples to checkin. This is at full discretion of the hotel management. No refund would be applicable in case the checkin is denied under such circumstances Pets are not allowed. Valid Photo ID required for check-in",
      hotel_facilities: "Doctor on Call|Laundry Service Available|Lift / Elevator|Parking Facilities Available|Front Desk|Power Backup|Campfire / Bon Fire|Internet Access Free|Outdoor Parking - Secured|Room Service|First-Aid Kit at Front Desk|Public Restrooms|Speciality Restaurant |Suites",
      hotel_star_rating: "3",
      image_count: "7",
      latitude: "32.537371",
      locality: "The Mall",
      longitude: "75.9824737",
      pageurl: "http://www.goibibo.com/hotels/detail/Dalhousie/hn/3084536095241319598/6911500444483426513/na/hq/",
      point_of_interest: "Dainkund Peak|Rang Mahal|The Mall",
      property_id: "HTLGBO1000075636",
      property_name: "AS Clarks inn",
      property_type: "Hotel",
      province: "Dalhousie",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::50|critical reviews::7|reviews with images::11",
      room_area: "",
      room_count: "10",
      room_facilities: "Room Service |Basic Bathroom Amenities|Cable / Satellite / Pay TV available|Video/ DVD/ CD Player Available|Ceiling Fan|Telephone",
      room_type: "Deluxe",
      similar_hotel: "https://www.goibibo.com/hotels/taj-palace-hotel-in-Dalhousie-93684368785637094|https://www.goibibo.com/hotels/mohan-palace-dalhousie-hotel-in-Dalhousie-7589037844666488149|https://www.goibibo.com/hotels/the-peace-channels-resort-pvt-ltd-hotel-in-Dalhousie-3007524930906412649|https://www.goibibo.com/hotels/bird-wood-cottages-hotel-in-Dalhousie-7403956779409111384|https://www.goibibo.com/hotels/comfort-inn-hotel-in-Dalhousie-8965800300122207241|https://www.goibibo.com/hotels/dalhousie-cottage--hotel-in-Dalhousie-256950066524513848|https://www.goibibo.com/hotels/alps-resorts-hotel-in-Dalhousie-510385221474854243|https://www.goibibo.com/hotels/pine-tree-cottages-hotel-in-Dalhousie-7213091951097031057|https://www.goibibo.com/hotels/bird-wood-cottage-hotel-in-Dalhousie-8467939720284842934|https://www.goibibo.com/hotels/megha-view-hotel-in-Dalhousie-668856007675483836|https://www.goibibo.com/hotels/grace-mount-hotel-hotel-in-Dalhousie-6727902601455776661",
      site_review_count: "57",
      site_review_rating: "4.2",
      site_stay_review_rating: "Service Quality::4.2|Amenities::4.1|Food and Drinks::4.1|Value for Money::4.1|Location::4.2|Cleanliness::4.1",
      sitename: "goibibo",
      state: "Himachal Pradesh",
      uniq_id: "091daef6f4cf8e8fc39bac2cf9342e79"
  },
  {
      additional_info: "",
      address: "Mullassery Building, Near Pallathuruthy Bridge, AC Road, Alleppey, Kerala, 688003",
      area: "Others",
      city: "Alleppey",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Booking rates will not be valid for Christmas and New year dates, High season and long weekend dates  extra supplement will be charged over and above the paid rates as per actual and hotel discretion.",
      hotel_facilities: "Doctor on Call",
      hotel_star_rating: "0",
      image_count: "3",
      latitude: "9.4980667",
      locality: "Others",
      longitude: "76.3388484",
      pageurl: "http://www.goibibo.com/hotels/detail/Alleppey/hn/31335703284729576/5652179225838307603/na/hq/",
      point_of_interest: "Champakulam Church|Alleppey Railway Station|Others|Alleppey Beach",
      property_id: "HTLGBO1000064884",
      property_name: "Beautiful Alleppey Tours Two Bedroom, Alleppey",
      property_type: "Houseboat",
      province: "Alleppey",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "2",
      room_facilities: "",
      room_type: "Deluxe Room",
      similar_hotel: "https://www.goibibo.com/hotels/ashtamudi-homestay-hotel-in-Alleppey-43591457381948561|https://www.goibibo.com/hotels/tours-to-kerala-,deluxe-houseboat-4-bed-room-hotel-in-Alleppey-2770632547694418870|https://www.goibibo.com/hotels/breeze-backwater-homes-hotel-in-Alleppey-5784067553981558692|https://www.goibibo.com/hotels/tours-to-kerala-,deluxe--houseboat-3-bed-room,alleppey-hotel-in-Alleppey-8683011031761158566|https://www.goibibo.com/hotels/marari-swapna-beach-villas-hotel-in-Alleppey-9183134278045524815|https://www.goibibo.com/hotels/karthiyayini-hotel-hotel-in-Alleppey-5930445054878031657|https://www.goibibo.com/hotels/marari-neena-beach-home-stay-hotel-in-Alleppey-5761570278440188677|https://www.goibibo.com/hotels/royal-rooms-hotel-in-Alleppey-4858109555754505066|https://www.goibibo.com/hotels/aamy's-home-stay-hotel-in-Alleppey-8524300706056458390|https://www.goibibo.com/hotels/tours-to-kerala-houseboat--hotel-in-Alleppey-3699883365950908946|https://www.goibibo.com/hotels/tours-to-kerala-,deluxe-3-bed-room-hotel-in-Alleppey-3032743791539180985|https://www.goibibo.com/hotels/white-saand-beach-resort(guest-house)-hotel-in-Alleppey-3392440814756307362",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Kerala",
      uniq_id: "78d6eb4657722af02cdbcabf1c579fb7"
  },
  {
      additional_info: "Room Service|Free Internet",
      address: "Sinhgad road pune",
      area: "Pune Bangalore Highway",
      city: "Pune",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 10:00 AM and the standard check-out time is 09:45 AM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Need ID proof at the time of check in Unmarried couples not allowed",
      hotel_facilities: "Business Center |Parking Facilities Available|24 Hour Front Desk|Internet Access Free|Room Service (24 Hours)|Outdoor Parking - Secured|Parking Facility|Suites",
      hotel_star_rating: "0",
      image_count: "2",
      latitude: "18.4788581929",
      locality: "Pune Bangalore Highway",
      longitude: "73.8223181405",
      pageurl: "http://www.goibibo.com/hotels/detail/Pune/hn/1554245012668028405/500962097627242132/na/hq/",
      point_of_interest: "Chaitanya Hospital|Lokmanya Hospitals Joint Replacement Center|Mai Mangeshkar Hospital|Deenanath Mangeshkar Hospital|saras baug|Pune Bangalore Highway|Anandibai Narhar Gadgil Hospital|Krishna Hospital|Parvati Hill|Cipla Cancer &amp; Aids Foundation Care &amp; Training Center|Cipla Cancer & Aids Foundation Care & Training Center",
      property_id: "HTLGBO1000057350",
      property_name: "Ashiyana",
      property_type: "Homestay",
      province: "Pune",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "",
      room_area: "",
      room_count: "5",
      room_facilities: "",
      room_type: "Double Room",
      similar_hotel: "https://www.goibibo.com/hotels/deccan-pavilion,-katraj-hotel-in-Pune-91667963394557272|https://www.goibibo.com/hotels/vishwas-lodging,-vadgaon-budruk-hotel-in-Pune-446963760871737779|https://www.goibibo.com/hotels/laxmi-krupa--service-apartments-hotel-in-Pune-6973606274385182621|https://www.goibibo.com/hotels/garuda-hotel-in-Pune-8103258813845343886|https://www.goibibo.com/hotels/popular-hotel-hotel-in-Pune-3674172992051290817|https://www.goibibo.com/hotels/choice-hostel-hotel-in-Pune-8584356398971945882|https://www.goibibo.com/hotels/rudra-residency-hotel-in-Pune-1292827501112254252",
      site_review_count: "",
      site_review_rating: "",
      site_stay_review_rating: "Service Quality::|Amenities::|Food and Drinks::|Value for Money::|Location::|Cleanliness::",
      sitename: "goibibo",
      state: "Maharashtra",
      uniq_id: "67c5e17d1829882a2eea640f7863eebc"
  },
  {
      additional_info: "Room Service",
      address: "Railway Station Rd,NEAR SHIVAJI STATUE,NANDED,MAHARASHTRA.",
      area: "Railway Station Rd",
      city: "Nanded",
      country: "India",
      crawl_date: "2016-07-24",
      guest_recommendation: "87",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 12:00 PM and the standard check-out time is 12:00 PM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly we do not allow Unmarried / unrelated Couples to check-in .This is at full discretion of the hotel management.No refund would be applicable in case the check-in denied under such circumstances. ID-proof mandatory to submit.",
      hotel_facilities: "Business Center |Doctor on Call|Laundry Service Available|24 Hour Front Desk|Power Backup|Room Service|CCTV",
      hotel_star_rating: "0",
      image_count: "4",
      latitude: "19.1382514",
      locality: "Railway Station Rd",
      longitude: "77.3209555",
      pageurl: "http://www.goibibo.com/hotels/detail/Nanded/hn/3336688138651690805/5937809647717405578/na/hq/",
      point_of_interest: "Railway Station Rd|Shri Guru Gobind Singh Ji Airport",
      property_id: "HTLGBO1000059830",
      property_name: "ASHIRWAD LODGING",
      property_type: "Hotel",
      province: "Nanded",
      qts: "2016-07-24 01:12:30 +0000",
      query_time_stamp: "2016-07-24 01:12:30 +0000",
      review_count_by_category: "positive reviews::28|critical reviews::13|reviews with images::6",
      room_area: "",
      room_count: "10",
      room_facilities: "",
      room_type: "NON AC DELUXE",
      similar_hotel: "https://www.goibibo.com/hotels/talha-residency-hotel-in-Nanded-4538879839221419096|https://www.goibibo.com/hotels/manju-palace-hotel-in-Nanded-1366275652046376140|https://www.goibibo.com/hotels/-hotel-teak-wood-executive-hotel-in-Nanded-7641914524792910111|https://www.goibibo.com/hotels/nagarjuna-hotel-in-Nanded-8311223135117889757|https://www.goibibo.com/hotels/bajaj-residency-hotel-in-Nanded-7021925862325996397|https://www.goibibo.com/hotels/nirmal-palace-hotel-in-Nanded-7262293829434036004|https://www.goibibo.com/hotels/city-pride-hotel-in-Nanded-8656685482364640335|https://www.goibibo.com/hotels/anuradha-palace-hotel-in-Nanded-6255510037831935627|https://www.goibibo.com/hotels/uma-executive-hotel-in-Nanded-9131883547607592222|https://www.goibibo.com/hotels/gn-executive-hotel-in-Nanded-1278568856959513855|https://www.goibibo.com/hotels/suraj-kanwar-hotel-hotel-in-Nanded-8409664547798650880",
      site_review_count: "41",
      site_review_rating: "3.2",
      site_stay_review_rating: "Service Quality::3.2|Amenities::3.1|Food and Drinks::3.9|Value for Money::3.6|Location::3.6|Cleanliness::2.9",
      sitename: "goibibo",
      state: "Maharashtra",
      uniq_id: "435632e2bd4d3b81f2e2ad2420769fdf"
  },
  {
      additional_info: "Room Service|Restaurant",
      address: "N.H 6, A.Katapali, Near Gosala",
      area: "Katapali",
      city: "Sambalpur",
      country: "India",
      crawl_date: "2016-06-26",
      guest_recommendation: "50",
      hotel_brand: "null",
      hotel_category: "regular",
      hotel_description: "The standard check-in time is 10:00 AM and the standard check-out time is 10:00 AM. Early check-in or late check-out is strictly subjected to availability and may be chargeable by the hotel. Any early check-in or late check-out request must be directed and reconfirmed with hotel directly Booking rates will not be valid for Christmas  New year dates, High season  long weekend dates  extra supplement will be charged over  above the paid rates as per actual  hotel discretion.",
      hotel_facilities: "Business Center |Doctor on Call|Parking Facilities Available|Front Desk|Multi Cuisine Restaurant |Medical Assistance Available|Gardens|Parking Facility|Room Service|Public Restrooms",
      hotel_star_rating: "2",
      image_count: "6",
      latitude: "21.4489781532",
      locality: "Katapali",
      longitude: "83.9125019492",
      pageurl: "http://www.goibibo.com/hotels/detail/Sambalpur/hn/7913407017336227693/5247331404537903379/na/hq/",
      point_of_interest: "Katapali",
      property_id: "HTLGBO1000071918",
      property_name: "Hotel Silver Moon",
      property_type: "Hotel",
      province: "Sambalpur",
      qts: "",
      query_time_stamp: "2016-06-26 05:31:53 +0000",
      review_count_by_category: "positive reviews::2|critical reviews::0|reviews with images::0",
      room_area: "",
      room_count: "8",
      room_facilities: "Room Service |Basic Bathroom Amenities| Hot / Cold Running Water|Housekeeping|Desk in Room|Toiletries",
      room_type: "Deluxe AC Room",
      similar_hotel: "https://www.goibibo.com/hotels/ashoka-hotel-hotel-in-Sambalpur-3023740046001100135|https://www.goibibo.com/hotels/royale-inn-hotel-in-Sambalpur-8846451189206531494|https://www.goibibo.com/hotels/niiki-resorts-pvt.ltd-hotel-in-Sambalpur-909070949384660053|https://www.goibibo.com/hotels/sheela-towers-private-limited-hotel-in-Sambalpur-4395037736284011454|https://www.goibibo.com/hotels/harjit-residency-hotel-in-Sambalpur-5356557434141159380|https://www.goibibo.com/hotels/upahar-palace-hotel-in-Sambalpur-8553641549103984054|https://www.goibibo.com/hotels/sujata-hotel-in-Sambalpur-4542242844450051116|https://www.goibibo.com/hotels/saket-hotel-in-Sambalpur-4513913612051371015|https://www.goibibo.com/hotels/apsara-hotel-in-Sambalpur-5374366415113109501",
      site_review_count: "2",
      site_review_rating: "4.3",
      site_stay_review_rating: "Service Quality::4.3|Amenities::4.3|Food and Drinks::4.3|Value for Money::4.3|Location::4.3|Cleanliness::4.3",
      sitename: "goibibo",
      state: "Orissa",
      uniq_id: "ae587589415630183abc91d5f2fd3de4"
  },
]
export { goibioData };
